import React, { useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Activity, AlertTriangle, CheckCircle2, Clock3 } from 'lucide-react';
import { dashboardAlerts,dashboardStats,recentVerdicts,severityCounts,techniques } from '../data/alerts.js';
import { SectionTitle,SeverityBadge,TopNav } from '../components/ui.jsx';

const icons=[Activity,AlertTriangle,CheckCircle2,Clock3];
function StatCard({stat,index}){const Icon=icons[index];return <article className={`stat-card ${stat.color}`}><div className="stat-label"><Icon size={15}/><span>{stat.label}</span></div><div className="stat-value">{stat.value} {stat.suffix&&<small>{stat.suffix}</small>}</div></article>}
function DonutChart(){const total=severityCounts.reduce((a,x)=>a+x.value,0),colors=['var(--red)','var(--amber)','var(--blue)','var(--green)'];let acc=0;const arcs=severityCounts.map((x,i)=>{const start=acc/total*100;acc+=x.value;return `${colors[i]} ${start}% ${acc}%`;});return <><div className="donut-wrap"><div className="donut" style={{background:`conic-gradient(${arcs.join(',')})`}}><div className="donut-hole"><strong>{total}</strong><span>ACTIVE</span></div></div></div><div className="legend-grid">{severityCounts.map((x,i)=><div key={x.label} className="legend-item"><i style={{background:colors[i]}}/><span>{x.label}</span><b>{x.value}</b></div>)}</div></>}
function AlertList({alerts}){const nav=useNavigate();return <div className="alert-list">{alerts.length?alerts.map(a=><button key={a.id} className={`alert-row ${a.severity.toLowerCase()}`} onClick={()=>nav(a.triage?`/triage/${a.triage}`:'/triage')}><span className="alert-row-main"><strong>{a.title}</strong><small><code>{a.id}</code><span>·</span><code>{a.time}</code><span>·</span><code>{a.ip}</code><span>·</span>{a.sourceLabel}</small></span><SeverityBadge value={a.severity}/></button>):<div className="no-results">No alerts match these filters.</div>}</div>}
export default function Dashboard(){const [source,setSource]=useState('All'),[severity,setSeverity]=useState('All');const filtered=useMemo(()=>dashboardAlerts.filter(a=>(source==='All'||a.source===source)&&(severity==='All'||a.severity===severity)),[source,severity]);return <div className="app-layout"><TopNav/><main className="dashboard-main"><section className="stats-grid">{dashboardStats.map((s,i)=><StatCard key={s.label} stat={s} index={i}/>)}</section><div className="dashboard-grid"><section className="card incoming-card"><div className="incoming-head"><SectionTitle aside={<span className="live-indicator"><i/> Live</span>}>Incoming Alerts</SectionTitle><div className="filters"><label><span className="sr-only">Filter by source</span><select value={source} onChange={e=>setSource(e.target.value)}><option>All</option><option>Splunk</option><option>Sentinel</option><option>QRadar</option></select></label><label><span className="sr-only">Filter by severity</span><select value={severity} onChange={e=>setSeverity(e.target.value)}><option>All</option>{['Critical','High','Medium','Low'].map(x=><option key={x}>{x}</option>)}</select></label></div></div><AlertList alerts={filtered}/></section><aside className="dashboard-side"><section className="card side-card severity-card"><SectionTitle>Severity Distribution</SectionTitle><DonutChart/></section><section className="card side-card mitre-card"><SectionTitle aside="12 detected today">Active MITRE Techniques</SectionTitle><div className="mitre-list">{techniques.map(t=><span key={t}>{t}</span>)}</div></section><section className="card side-card verdicts-card"><SectionTitle>Recent Verdicts</SectionTitle><div className="verdict-list">{recentVerdicts.map(v=><div className="verdict-row" key={v.name}><i className={v.type}/><strong>{v.name}</strong><small>{v.time}</small><b className={v.type}>{v.risk}</b></div>)}</div></section></aside></div></main></div>}
