import React, { useEffect, useMemo, useState } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { Check, CheckCircle2, Circle, Clipboard, Eye, FileText, LoaderCircle, ShieldAlert, ShieldCheck, TriangleAlert } from 'lucide-react';
import { triageAlerts } from '../data/triage.js';
import { Button,EmptyState,FilterPills,SectionTitle,SeverityBadge,TopNav } from '../components/ui.jsx';

const stages=['Parsing','Generating Queries','Retrieving Intel','Reranking','Computing Risk','Generating Verdict'];
function QueueRow({alert,selected,onClick}){return <button className={`queue-row ${selected?'selected':''}`} onClick={onClick}><span className="queue-top"><strong>{alert.title}</strong><SeverityBadge value={alert.severity}/></span><span className="queue-meta"><code>{alert.id}</code><span>·</span><code>{alert.time}</code><span>·</span><code>{alert.ip}</code></span></button>}
function VerdictBanner({alert}){const Icon=alert.verdict==='escalate'?TriangleAlert:alert.verdict==='monitor'?Eye:CheckCircle2;const headline=alert.verdict==='escalate'?'Escalate — Tier-2 Investigation Required':alert.verdict==='monitor'?'Monitor — Analyst Review Recommended':'Resolve — No Immediate Action Required';return <div className={`verdict-banner ${alert.verdict}`}><Icon/><div><h2>{headline}</h2><p><code>Incident ID: {alert.id}</code><span>·</span><code>Ingested at {alert.time}</code></p></div><span className="verdict-action">{alert.verdict==='escalate'?'ESCALATE (TIER 2)':alert.verdict.toUpperCase()}</span></div>}
function RiskBar({score}){const tone=score>80?'red':score>55?'amber':'blue';return <section className="risk-card"><div className="risk-head"><span>RISK SCORE</span><strong className={tone}><code>{score}/100</code></strong></div><div className="risk-track"><span className={tone} style={{width:`${score}%`}}/></div><div className="risk-foot"><span>Threshold: 80+ Escalate · 55–79 Monitor · &lt;55 Resolve</span><span>Risk score</span></div></section>}
function AnalysisResult({alert}){const [done,setDone]=useState({});return <div className="analysis-result"><VerdictBanner alert={alert}/><RiskBar score={alert.score}/><section className="result-section"><SectionTitle>MITRE ATT&amp;CK Techniques</SectionTitle><div className="mitre-list">{alert.mitre.length?alert.mitre.map(t=><span key={t}>{t}</span>):<em>None</em>}</div></section><section className="result-section"><SectionTitle>Extracted IOCs &amp; Indicators</SectionTitle><div className="ioc-grid">{alert.iocs.map(i=><div className="ioc-item" key={i}><span>#</span><code>{i}</code><button aria-label={`Copy ${i}`} onClick={()=>navigator.clipboard?.writeText(i)}><Clipboard/></button></div>)}</div></section><section className="result-section"><SectionTitle aside="Vector match threshold &gt; 0.65">Retrieved Evidence (RAG Pipeline)</SectionTitle><div className="evidence-list">{alert.evidence.map((e,i)=><article className={`evidence-card ${e.tier.toLowerCase()}`} key={e.source}><div className="evidence-head"><code>{e.source}</code><span className={`evidence-tier ${e.tier.toLowerCase()}`}>{e.tier}</span><span className="score-badge">score {e.score}</span></div><p>{e.body}</p></article>)}</div></section><section className="result-section"><SectionTitle>AI Reasoning</SectionTitle><div className="reasoning-block">{alert.reasoning}</div></section><section className="result-section"><SectionTitle>Investigation Steps</SectionTitle><div className="investigation-list">{alert.steps.map((s,i)=>{const priority=`P${Math.min(i+1,4)}`;return <div className={`investigation-step ${done[i]?'done':''}`} key={s}><span className={`priority ${priority.toLowerCase()}`}>{priority}</span><span className="step-index">{i+1}.</span><p>{s}</p><button aria-label={done[i]?'Mark step incomplete':'Mark step complete'} aria-pressed={!!done[i]} onClick={()=>setDone(d=>({...d,[i]:!d[i]}))}>{done[i]?<CheckCircle2/>:<Circle/>}</button></div>})}</div></section></div>}
function Analyzing({step}){return <div className="analyzing"><LoaderCircle className="spin"/><h2>ARIA is analyzing<span className="animated-dots">...</span></h2><p>Processing alert and retrieving relevant intelligence.</p><div className="analysis-steps">{stages.map((s,i)=><div className={i<step?'complete':i===step?'current':''} key={s}>{i<step?<Check size={14}/>:<span className="step-dot"/>}{s}</div>)}</div></div>}
export default function Triage(){const {alertId}=useParams(),nav=useNavigate();const [selected,setSelected]=useState(null),[filter,setFilter]=useState('All'),[phase,setPhase]=useState('empty'),[step,setStep]=useState(0),[toast,setToast]=useState('');const visible=useMemo(()=>triageAlerts.filter(a=>filter==='All'||a.severity===filter),[filter]);
 useEffect(()=>{if(alertId){const match=triageAlerts.find(a=>a.id===alertId);if(match){setSelected(match);setPhase('analyzing');setStep(0)}else{setSelected(null);setPhase('empty')}}else{setSelected(null);setPhase('empty')}},[alertId]);
 useEffect(()=>{if(!selected||phase!=='analyzing')return;let stage=0,finishId;setStep(0);const id=setInterval(()=>{stage+=1;setStep(stage);if(stage>=6){clearInterval(id);finishId=setTimeout(()=>setPhase('result'),180)}},190);return()=>{clearInterval(id);clearTimeout(finishId)}},[selected,phase]);
 const choose=a=>{setSelected(a);setPhase('analyzing');setStep(0);nav(`/triage/${a.id}`,{replace:false})};const notify=t=>{setToast(t);setTimeout(()=>setToast(''),2200)};
 return <div className="app-layout triage-app"><TopNav triage/><main className="triage-layout"><aside className="queue-panel"><div className="queue-heading"><SectionTitle aside={<><i/> 6 pending</>}>Alert Queue</SectionTitle><FilterPills options={['All','Critical','High','Medium','Low']} value={filter} onChange={setFilter}/></div><div className="queue-list">{visible.map(a=><QueueRow key={a.id} alert={a} selected={selected?.id===a.id} onClick={()=>choose(a)}/> )}</div><div className="queue-status"><i/> AUTONOMOUS ENGINE ACTIVE</div></aside><section className="detail-panel">{phase==='empty'&&<EmptyState/>}{phase==='analyzing'&&<Analyzing step={step}/>} {phase==='result'&&selected&&<><div className="result-scroll"><AnalysisResult key={selected.id} alert={selected}/></div><div className="action-bar"><div className="action-context"><span className="live-dot"/> Analysis complete</div><div className="action-buttons"><Button tone="green" onClick={()=>notify('Report generation is a placeholder.')}><FileText/>Generate Report</Button><Button tone="red" onClick={()=>notify('Escalation is a placeholder.')}><ShieldAlert/>Escalate to Tier-2</Button></div></div></>}</section></main>{toast&&<div className="toast" role="status">{toast}</div>}</div>}
