import React, { useEffect, useRef, useState } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { Bell, ShieldCheck, Sun, Moon, UserRound, ChevronDown, LogOut, Settings, User, Clock3, CircleHelp } from 'lucide-react';
import { useTheme } from '../context/ThemeContext.jsx';

export function ThemeToggle({ fixed=false }) { const {theme,toggle}=useTheme(); return <button className={`icon-button theme-toggle ${fixed?'theme-fixed':''}`} onClick={toggle} aria-label={`Switch to ${theme==='dark'?'light':'dark'} mode`} title={`Switch to ${theme==='dark'?'light':'dark'} mode`}>{theme==='dark'?<Sun/>:<Moon/>}</button>; }
export function LiveClock(){ const [time,setTime]=useState(()=>new Date()); useEffect(()=>{const id=setInterval(()=>setTime(new Date()),1000);return()=>clearInterval(id)},[]); return <div className="clock"><Clock3 size={14}/><span>{time.toLocaleTimeString('en-GB',{hour12:false,timeZone:'UTC'})} UTC</span></div>; }
function UserMenu(){ const [open,setOpen]=useState(false); const ref=useRef(null), nav=useNavigate(); useEffect(()=>{const listener=e=>{if(e.key==='Escape')setOpen(false);if(ref.current&&!ref.current.contains(e.target))setOpen(false)};document.addEventListener('mousedown',listener);document.addEventListener('keydown',listener);return()=>{document.removeEventListener('mousedown',listener);document.removeEventListener('keydown',listener)}},[]); return <div ref={ref} className="user-menu"><button className="avatar-button" aria-label="Open user menu" aria-expanded={open} onClick={()=>setOpen(v=>!v)}><span>AN</span><ChevronDown size={14}/></button>{open&&<div className="menu-popover"><button><User size={15}/>Profile</button><button><Settings size={15}/>Settings</button><div className="menu-divider"/><button onClick={()=>nav('/login')}><LogOut size={15}/>Logout</button></div>}</div>; }
export function TopNav({triage=false}){ const loc=useLocation(), nav=useNavigate(); const tabs=[['Dashboard','/dashboard'],['Alerts','/triage'],['Threat Intel',null],['Analytics',null],['Settings',null]]; return <header className="top-nav"><button className="brand" onClick={()=>nav('/dashboard')}><ShieldCheck/><span>ARIA</span></button>{triage&&<button className="back-link" onClick={()=>nav('/dashboard')}>‹ <span>Back to Dashboard</span></button>}<nav className="nav-tabs">{tabs.map(([label,path])=><button key={label} className={`nav-tab ${((triage&&label==='Alerts')||(!triage&&label==='Dashboard'))?'active':''}`} onClick={()=>path&&nav(path)}>{label}</button>)}</nav><div className="nav-utilities"><LiveClock/><ThemeToggle/><button className="icon-button notification" aria-label="Notifications"><Bell/><i/></button><UserMenu/></div></header>; }
export function SeverityBadge({value}){return <span className={`severity-badge ${value.toLowerCase()}`}>{value}</span>}
export function Button({children,onClick,tone='primary',className='',...props}){return <button className={`button ${tone} ${className}`} onClick={onClick} {...props}>{children}</button>}
export function SectionTitle({children,aside}){return <div className="section-title"><h2>{children}</h2>{aside&&<span>{aside}</span>}</div>}
export function FilterPills({options,value,onChange}){return <div className="filter-pills" role="group">{options.map(o=><button key={o} aria-pressed={o===value} className={o===value?'selected':''} onClick={()=>onChange(o)}>{o}</button>)}</div>}
export function EmptyState(){return <div className="empty-state"><CircleHelp size={26}/><h2>Select an alert to triage</h2><p>Choose an alert from the queue to begin analysis.</p></div>}
export function AuthLayout({children}){return <main className="auth-layout"><ThemeToggle fixed/><div className="auth-card">{children}</div><div className="auth-foot"><span>⌑</span> Secured with AES-256 encryption</div></main>}
